/* Generated by GOB (v2.0.12)   (do not edit directly) */

#ifndef __GEM_BUTTON_BOX_EDITOR_PRIVATE_H__
#define __GEM_BUTTON_BOX_EDITOR_PRIVATE_H__

#include "gem-button-box-editor.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#line 14 "gem-button-box-editor.gob"

#include "gem-button-box-button-bless.h"
#include "gem-button-box-button-bless-editor.h"

#line 19 "gem-button-box-editor-private.h"
struct _GemButtonBoxEditorPrivate {
#line 74 "gem-button-box-editor.gob"
	GemButtonBox * button_box;
#line 75 "gem-button-box-editor.gob"
	GtkListStore * store;
#line 76 "gem-button-box-editor.gob"
	GtkWidget * w_tree_view;
#line 77 "gem-button-box-editor.gob"
	GtkWidget * w_entry_label;
#line 78 "gem-button-box-editor.gob"
	GtkWidget * w_entry_balloon;
#line 79 "gem-button-box-editor.gob"
	GtkWidget * w_use_glade_check;
#line 80 "gem-button-box-editor.gob"
	GtkWidget * w_glade_filename_box;
#line 81 "gem-button-box-editor.gob"
	GtkWidget * w_glade_filechooser_button;
#line 82 "gem-button-box-editor.gob"
	gboolean is_inserting;
#line 39 "gem-button-box-editor-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
