/* Generated by GOB (v2.0.12)   (do not edit directly) */

#ifndef __GEM_BUTTON_BOX_BUTTON_PRIVATE_H__
#define __GEM_BUTTON_BOX_BUTTON_PRIVATE_H__

#include "gem-button-box-button.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct _GemButtonBoxButtonPrivate {
#line 40 "src/gem-button-box-button.gob"
	gchar * script;
#line 41 "src/gem-button-box-button.gob"
	gchar * label;
#line 42 "src/gem-button-box-button.gob"
	GemCmdEval * cmd_eval;
#line 43 "src/gem-button-box-button.gob"
	GtkWidget * menu;
#line 44 "src/gem-button-box-button.gob"
	GtkWidget * w_button_box;
#line 24 "gem-button-box-button-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
