/* Generated by GOB (v2.0.12)   (do not edit directly) */

#ifndef __GEM_BUTTON_BOX_PRIVATE_H__
#define __GEM_BUTTON_BOX_PRIVATE_H__

#include "gem-button-box.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#line 20 "src/gem-button-box.gob"

#include <glade/glade-parser.h>
#include <glade/glade-xml.h>

#line 19 "gem-button-box-private.h"
struct _GemButtonBoxPrivate {
#line 89 "src/gem-button-box.gob"
	GtkWidget * w_table;
#line 90 "src/gem-button-box.gob"
	GtkWidget * w_toolbar;
#line 91 "src/gem-button-box.gob"
	GtkWidget * w_notebook;
#line 92 "src/gem-button-box.gob"
	GtkWidget * w_glade_widget;
#line 93 "src/gem-button-box.gob"
	GemCmdEval * cmd_eval;
#line 94 "src/gem-button-box.gob"
	GPtrArray * button_list;
#line 95 "src/gem-button-box.gob"
	GPtrArray * glade_widget_list;
#line 96 "src/gem-button-box.gob"
	gchar * glade_filename;
#line 97 "src/gem-button-box.gob"
	gboolean use_glade;
#line 98 "src/gem-button-box.gob"
	GladeInterface * gif;
#line 99 "src/gem-button-box.gob"
	GladeXML * xml;
#line 43 "gem-button-box-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
