/* Generated by GOB (v2.0.12)   (do not edit directly) */

#ifndef __GEM_BUTTON_BOX_PRIVATE_H__
#define __GEM_BUTTON_BOX_PRIVATE_H__

#include "gem-button-box.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */


#line 20 "src/gem-button-box.gob"

#include <glade/glade-parser.h>
#include <glade/glade-xml.h>

#line 19 "gem-button-box-private.h"
struct _GemButtonBoxPrivate {
#line 78 "src/gem-button-box.gob"
	GtkWidget * w_table;
#line 79 "src/gem-button-box.gob"
	GtkWidget * w_toolbar;
#line 80 "src/gem-button-box.gob"
	GtkWidget * w_notebook;
#line 81 "src/gem-button-box.gob"
	GtkWidget * w_glade_widget;
#line 82 "src/gem-button-box.gob"
	GemCmdEval * cmd_eval;
#line 83 "src/gem-button-box.gob"
	GPtrArray * button_list;
#line 84 "src/gem-button-box.gob"
	GPtrArray * glade_widget_list;
#line 85 "src/gem-button-box.gob"
	gchar * glade_filename;
#line 86 "src/gem-button-box.gob"
	gboolean use_glade;
#line 87 "src/gem-button-box.gob"
	GladeInterface * gif;
#line 88 "src/gem-button-box.gob"
	GladeXML * xml;
#line 43 "gem-button-box-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
