/* Generated by GOB (v2.0.12)   (do not edit directly) */

#ifndef __GEM_BUTTON_BOX_BUTTON_BLESS_EDITOR_PRIVATE_H__
#define __GEM_BUTTON_BOX_BUTTON_BLESS_EDITOR_PRIVATE_H__

#include "gem-button-box-button-bless-editor.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct _GemButtonBoxButtonBlessEditorPrivate {
#line 42 "src/gem-button-box-button-bless-editor.gob"
	GtkWidget * button_box_button;
#line 43 "src/gem-button-box-button-bless-editor.gob"
	GtkTextBuffer * text_buffer;
#line 44 "src/gem-button-box-button-bless-editor.gob"
	GtkWidget * w_entry_label;
#line 20 "gem-button-box-button-bless-editor-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
