/* Generated by GOB (v2.0.12)   (do not edit directly) */

#ifndef __GEM_BUTTON_BOX_BUTTON_EDITOR_PRIVATE_H__
#define __GEM_BUTTON_BOX_BUTTON_EDITOR_PRIVATE_H__

#include "gem-button-box-button-editor.h"

#ifdef __cplusplus
extern "C" {
#endif /* __cplusplus */

struct _GemButtonBoxButtonEditorPrivate {
#line 39 "src/gem-button-box-button-bless-editor.gob"
	GtkWidget * button_box_button;
#line 40 "src/gem-button-box-button-bless-editor.gob"
	GtkTextBuffer * text_buffer;
#line 41 "src/gem-button-box-button-bless-editor.gob"
	GtkWidget * w_entry_label;
#line 20 "gem-button-box-button-editor-private.h"
};

#ifdef __cplusplus
}
#endif /* __cplusplus */

#endif
